--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx
  name: nginx-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: "gcr.io/${GOOGLE_CLOUD_PROJECT}/data-science-on-gcp:v2"
          name: data-science-on-gcp
          ports: 
            - 
              containerPort: 80
